name: Generate Snake
on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual trigger
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@v3
        with:
          github_user_name: jesusestime
          outputs: dist/github-contribution-grid-snake.svg
      - name: Push to main
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Update snake animation" || echo "No changes to commit"
          git push origin main
